[package]
authors = ["robiot"]
edition = "2018"
license = "MIT"
name = "searchpath"
readme = "README.md"
repository = "https://github.com/robiot/searchpath"
version = "0.1.0"

[dependencies]
libc = "0.2"
